// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uegvumnkmniijdcmvtas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlZ3Z1bW5rbW5paWpkY212dGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzE4OTksImV4cCI6MjA2NjAwNzg5OX0.SILndHLCHwugT3iM1FuHOeIsaY1ooMXUWghxz_P2DNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);